### ISSUE TITLE
Need to start on the login for both facilities and musicians

### ISSUE THREAD

**Issue by abw1914** [abw1914/EncoreLinkV2#1]
login

**Comment by gea-07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create initial Facility Page](https://trello.com/c/iqQBnNT6/1-create-initial-facility-page)

**Comment by jqn** [comment]
putting this on hold in favor of https://github.com/abw1914/EncoreLink/issues/19

**Comment by jqn** [comment]
Closing this issue in favor of #19
