### ISSUE TITLE
Develop Mobile Specific Wireframes

### ISSUE THREAD

**Issue by abw1914** [abw1914/EncoreLinkV2#15]
Original project wireframes can be found here:

https://docs.google.com/document/d/1doA7VpzJOLWkAjNNI8fbHDK0z640fHT8AcvAKHXXjY0/edit?usp=sharing

**Comment by jqn** [comment]
@baghaii these wireframes look great, does anyone have any suggestions or changes?
https://docs.google.com/presentation/d/1nRNE561NkEDxkvPoz3HRocRBePc4lXBH7Dl7in7VenE/edit

**Comment by jqn** [comment]
Closing this issue - wireframes are complete and reviewed
