### ISSUE TITLE
Develop Events Class

### ISSUE THREAD

**Issue by abw1914** [abw1914/EncoreLinkV2#3]
Need to develop:

- Create event method

- Edit event method

- Delete event method

**Comment by baghaii** [comment]
It should just be an Event class. Creating and deleting events should be methods in the class.

**Comment by baghaii** [comment]
Aaron, do you remember what the fields for the events were? I remember they had an ownerID, probably a start time, and an end time.

**Comment by abw1914** [comment]
Here you go...
 //this is for the EncoreLink Events get requests
final String eventName;
final String date;
final String notes;
final String location;
final String endDate;
final String createdDate;
final int eventId;

**Comment by jqn** [comment]
@abw1914 can I please get credentials to access the encorelink site to review this.

**Comment by jqn** [comment]
Closing this in a effort to clean up repo. Please feel free to reopen if relevant.
