### ISSUE TITLE
Develop the AboutUs 

### ISSUE THREAD

**Issue by abw1914** [abw1914/EncoreLinkV2#6]
Start writing app description

**Comment by jqn** [comment]
@raemacias could you please look at this issue a see if it's still valid. I'm going through the issues and cleaning/closing them depending on their state.

**Comment by raemacias** [comment]
@jqn I have not done anything with this. These were issues when first discussing the project and what we might need.

**Comment by jqn** [comment]
Thanks @raemacias I'll close this issue.
