### ISSUE TITLE
Event Class Database Schema 

### ISSUE THREAD

**Issue by abw1914** [abw1914/EncoreLinkV2#7]
Here are the fields for each music event:

"name": "string",
    "date": "2018-02-06T02:10:54.119Z",
    "notes": "string",
    "location": "string",
    "endDate": "2018-02-06T02:10:54.119Z",
    "created": "2018-02-06T02:10:54.119Z",
    "id": 0,
    "ownerId": 0

Need class a createEvent class for music facilities

**Comment by jqn** [comment]
@abw1914 Can we please see if this is still relevant.

**Comment by jqn** [comment]
Closing this in a effort to clean up repo. Please feel free to reopen if relevant.
